import { Language } from "./language-type";

export const ENG: Language = {
    'one': 'one',
    'Sunday': 'Sunday',
    'Monday': 'Monday',
    'Tuesday': 'Tuesday',
    'Wednesday': 'Wednesday',
    'Thursday': 'Thursday',
    'Friday': 'Friday',
    'Saturday': 'Saturday',
    'days': 'days',
    'lvl': 'lvl',
    'greatYouGot': 'Great! you got',
    'xpForYouLevel': 'xp for you level',
    'ephirForUpdateTargets': 'ephir for update your targets',
    'coinsToPurchaseCupons': 'coins to purchase coupons',
    'ballsToPurchasePrizes': 'balls to purchase prizes',
    'regularCouponForFreePurchase': 'a regular coupon for a free purchase of any daily prize',
    'couponForFreePurchase': 'coupon for free purchase of any prize',
    'get': 'Get',
    'takeTest': 'Do you just want to take the test?',
    'Target': 'Target',
    'Prize': 'Prize',
    'points': 'points',
    'recent': 'Recent',
    'transactions': 'Transactions',
    'deleted': 'Deleted',
    'shureDeleteOperation': 'Are you sure you want to delete the operation?',
    'deleteOperation': 'Delete operation?',
    'emptyOperations': 'Make a transaction to make it appear here',
    'timeToTest': 'Time to take the test!',
    'timeToTestMessage': 'Dont forget to take the daily test',
    'stepNameTitle': 'Name',
    'stepTypeTitle': 'Type',
    'stepDifficultyTitle': 'Difficulty',
    'stepPriceTitle': 'Price',
    'stepTargetNameMessage': 'Enter name and description',
    'stepTargetTypeMessage': 'Select target type',
    'stepTargetDifficultyMessage': 'Difficulty affects the reward',
    'stepPrizeTypeMessage': 'Select the type',
    'stepPrizeNameMessage': 'Write the name',
    'stepPrizePriceMessage': 'Specify the price',
    'delete': 'Delete',
    'namePlaceholder': 'Name...',
    'descriptionPlaceholder': 'Description...',
    'typeDailyName': 'Daily goal',
    'typeDailyDesc': 'Repeats every day. Perfect for building habits',
    'typeOneTimeName': 'One-time',
    'typeOneTimeDesc': 'Completed once, then disappears',
    'typeReminderName': 'Reminders',
    'typeReminderDesc': 'Notifies at the right time, rewards on completion, then disappears',
    'typeBigGoalName': 'Big goal',
    'typeBigGoalDesc': 'A big goal comes with a big reward and a special congratulation',
    'typeDurationName': 'Duration goal',
    'typeDurationDesc': 'Lasts a certain period. Fail it and you\'ll only get part of the reward',
    'typeProgressiveName': 'Progressive goal',
    'typeProgressiveDesc': 'Shows current progress toward the goal. Reward for each step and for reaching the goal',
    'typeExamplePrefix': 'For example: ',
}