import { Language } from "./language-type";


export const RU: Language = {
    'one': 'один',
    'Sunday': 'Воскресенье',
    'Monday': 'Понедельник',
    'Tuesday': 'Вторник',
    'Wednesday': 'Среда',
    'Thursday': 'Четверг',
    'Friday': 'Пятница',
    'Saturday': 'Суббота',
    'days': 'дней',
    'lvl': 'уровень',
    'greatYouGot': 'Поздравляем! вы получили',
    'xpForYouLevel': 'опыт для твоего уровня',
    'ephirForUpdateTargets': 'эфир для улучшения твоих целей',
    'coinsToPurchaseCupons': 'коинов для покупки купонов',
    'ballsToPurchasePrizes': 'баллов для покупки призов',
    'regularCouponForFreePurchase': 'обычный купон для покупки ежедневных призов',
    'couponForFreePurchase': 'купон для бесплатной покупки любого приза',
    'get': 'Получить',
    'takeTest': 'Вы можете просто пройти тест',
    'Target': 'Цели',
    'Prize': 'Призы',
    'points': 'пунктов',
    'recent': 'Последние',
    'transactions': 'Транзакции',
    'deleted': 'Удалить',
    'shureDeleteOperation': 'Вы уверены что хотите удалить эту операцию?',
    'deleteOperation': 'Удалить операцию?',
    'emptyOperations': 'Совершите транзакцию чтобы она отобразилась здесь',
    'timeToTest': 'Время пройти тест!',
    'timeToTestMessage': 'Не забудьте пройти ежедневный тест',
    'stepNameTitle': 'Название',
    'stepTypeTitle': 'Тип',
    'stepDifficultyTitle': 'Сложность',
    'stepPriceTitle': 'Цена',
    'stepTargetNameMessage': 'Введите название и описание',
    'stepTargetTypeMessage': 'Выберите тип цели',
    'stepTargetDifficultyMessage': 'Сложность влияет на награду',
    'stepPrizeTypeMessage': 'Выберите тип',
    'stepPrizeNameMessage': 'Введите название',
    'stepPrizePriceMessage': 'Укажите цену',
    'delete': 'Удалить',
    'namePlaceholder': 'Название...',
    'descriptionPlaceholder': 'Описание...',
    'typeDailyName': 'Ежедневная цель',
    'typeDailyDesc': 'Повторяется каждый день. Идеально для формирования привычек',
    'typeOneTimeName': 'Одноразовая',
    'typeOneTimeDesc': 'Выполняется один раз, после чего пропадает',
    'typeReminderName': 'Напоминания',
    'typeReminderDesc': 'Уведомляет в нужное время, награждает за выполнение, пропадает',
    'typeBigGoalName': 'Крупная цель',
    'typeBigGoalDesc': 'С большой целью приходит большая награда, и особое поздравление',
    'typeDurationName': 'Продолжительная цель',
    'typeDurationDesc': 'Длится определённый период. Если провалишь получишь только часть награды',
    'typeProgressiveName': 'Прогрессивная цель',
    'typeProgressiveDesc': 'Показывает текущий прогресс, насколько близок к цели. Награда за каждый шаг и за достижение цели',
    'typeExamplePrefix': 'Например: ',
    'stepDateTitle': 'Дата',
    'stepDateMessage': 'Выберите дату',
    'stepGoalTitle': 'Цель',
    'stepGoalMessage': 'Укажите конечное значение',
}